# Create the docker environment to run Apache Beam

version: '3'
services:
  python_beam:
    build:
      context: ./
      dockerfile: python/Dockerfile
    volumes:
        - ./data:/data
        - ./app:/app
        - ./result:/result
    container_name: python_runtime