# Create the docker environment to run Apache Beam

version: '3'
services:
  python_beam:
    container_name: python_runtime
    build:
      context: ./
      dockerfile: python/Dockerfile
    volumes:
        - ./data:/data
        - ./app:/app
        - ./result:/result
        - $HOME/.gcp/terraform-service.json:/home/app/.gcp/credentials:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/app/.gcp/credentials